In [34]:
import sqlite3 as db
import pandas as pd
# Create your connection.
df = pd.read_csv('/Users/badewaaderogba/Desktop/mydjango/media/upload_csv/promoteur_immo_V222.csv', delimiter=';')

In [37]:
df

,id,id_lot,nb_piece,typologie,prix_tva_reduite,prix_tva_normale,prix_HT,prix_m2_HT,prix_m2_TTC,surface,...,balcony,garden,parking,nom_programme,ville,departement,date_fin_programme,adresse_entiere,promoteur,date_extraction
0,0,42_4_GardenCity-Inten'City_Bouygues,2,Appartement,NaN,172500.0000,143750.00,3347.69,4017.23,42.94,...,True,False,1,Garden City - Inten'City,Clermont-Ferrand,63,fevrier 2024,RUE CHAMPFLEURI 63100 Clermont-Ferrand,Bouygues,2021-11-08
1,1,45_2_GardenCity-Inten'City_Bouygues,2,Appartement,NaN,179500.0000,149583.33,3267.44,3920.93,45.78,...,True,False,1,Garden City - Inten'City,Clermont-Ferrand,63,fevrier 2024,RUE CHAMPFLEURI 63100 Clermont-Ferrand,Bouygues,2021-11-08
2,2,45_1_GardenCity-Inten'City_Bouygues,2,Appartement,NaN,182500.0000,152083.33,3337.36,4004.83,45.57,...,False,False,1,Garden City - Inten'City,Clermont-Ferrand,63,fevrier 2024,RUE CHAMPFLEURI 63100 Clermont-Ferrand,Bouygues,2021-11-08
3,3,45_2__1_GardenCity-Inten'City_Bouygues,2,Appartement,NaN,184500.0000,153750.00,3373.93,4048.72,45.57,...,True,False,1,Garden City - Inten'City,Clermont-Ferrand,63,fevrier 2024,RUE CHAMPFLEURI 63100 Clermont-Ferrand,Bouygues,2021-11-08
4,4,67_1_GardenCity-Inten'City_Bouygues,3,Appartement,NaN,236500.0000,197083.33,2905.55,3486.66,67.83,...,True,False,1,Garden City - Inten'City,Clermont-Ferrand,63,fevrier 2024,RUE CHAMPFLEURI 63100 Clermont-Ferrand,Bouygues,2021-11-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2746,2746,80_6_FaubourgMazargues_Bouygues,4,Appartement,NaN,501500.0000,417916.67,5196.03,6235.24,80.43,...,True,False,1,Faubourg Mazargues,Marseille,13,novembre 2022,14 avenue de Lattre de Tassigny 13009 Marseille,Bouygues,2021-11-08
2747,2747,99_6_FaubourgMazargues_Bouygues,4,Appartement,NaN,598500.0000,498750.00,5016.09,6019.31,99.43,...,True,False,1,Faubourg Mazargues,Marseille,13,novembre 2022,14 avenue de Lattre de Tassigny 13009 Marseille,Bouygues,2021-11-08
2748,2748,96_6_ChateauValmante-ADMIR'_Bouygues,5,Appartement,NaN,767500.0000,639583.33,6610.68,7932.82,96.75,...,False,False,1,Chateau Valmante - ADMIR',Marseille,13,fevrier 2023,143 TRAVERSE DE LA GOUFFONNE 13009 Marseille,Bouygues,2021-11-08
2749,2749,96_6__1_ChateauValmante-ADMIR'_Bouygues,5,Appartement,NaN,809000.0000,674166.67,6968.13,8361.76,96.75,...,False,False,1,Chateau Valmante - ADMIR',Marseille,13,fevrier 2023,143 TRAVERSE DE LA GOUFFONNE 13009 Marseille,Bouygues,2021-11-08
2750,2750,38_2_VIANATURA_Bouygues,2,Appartement,173196.0,197000.1896,164166.82,4266.29,5119.55,38.48,...,False,False,1,VIA NATURA,Marseille,13,fevrier 2022,139 Avenue de la Croix Rouge 13013 Marseille,Bouygues,2021-11-08

In [36]:
tf = df[df.balcony == True]
conn = db.connect('/Users/badewaaderogba/Desktop/mydjango/postgres_django/db.sqlite3')
tf.to_sql(name='immo_bien', con=conn, if_exists='append')

IntegrityError: UNIQUE constraint failed: immo_bien.Id

In [18]:
import sqlite3
conn = sqlite3.connect('/Users/badewaaderogba/Desktop/mydjango/postgres_django/db.sqlite3')
df = pd.read_sql_query("SELECT * FROM immo_bien", conn)

In [19]:
df

,Id,id_lot,nb_piece,typologie,prix_tva_reduite,prix_tva_normale,prix_HT,prix_m2_HT,prix_m2_TTC,orientation,...,ville,departement,date_fin_programme,adresse_entiere,date_extraction,surface,etage,nom_programme,promoteur,index
0,0,42_4_GardenCity-Inten'City_Bouygues,2,Appartement,NaN,172500.0,143750.00,3347.69,4017.23,N,...,Clermont-Ferrand,63,fevrier 2024,RUE CHAMPFLEURI 63100 Clermont-Ferrand,2021-11-08,42.94,4.0,Garden City - Inten'City,Bouygues,0.0
1,1,45_2_GardenCity-Inten'City_Bouygues,2,Appartement,NaN,179500.0,149583.33,3267.44,3920.93,O,...,Clermont-Ferrand,63,fevrier 2024,RUE CHAMPFLEURI 63100 Clermont-Ferrand,2021-11-08,45.78,2.0,Garden City - Inten'City,Bouygues,1.0
2,3,45_2__1_GardenCity-Inten'City_Bouygues,2,Appartement,NaN,184500.0,153750.00,3373.93,4048.72,O,...,Clermont-Ferrand,63,fevrier 2024,RUE CHAMPFLEURI 63100 Clermont-Ferrand,2021-11-08,45.57,2.0,Garden City - Inten'City,Bouygues,3.0
3,4,67_1_GardenCity-Inten'City_Bouygues,3,Appartement,NaN,236500.0,197083.33,2905.55,3486.66,E,...,Clermont-Ferrand,63,fevrier 2024,RUE CHAMPFLEURI 63100 Clermont-Ferrand,2021-11-08,67.83,1.0,Garden City - Inten'City,Bouygues,4.0
4,5,69_1_GardenCity-Inten'City_Bouygues,3,Appartement,NaN,239500.0,199583.33,2869.23,3443.07,E,...,Clermont-Ferrand,63,fevrier 2024,RUE CHAMPFLEURI 63100 Clermont-Ferrand,2021-11-08,69.56,1.0,Garden City - Inten'City,Bouygues,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1038,2743,80_3_FaubourgMazargues_Bouygues,4,Appartement,NaN,390500.0,325416.67,4029.93,4835.91,NO,...,Marseille,13,novembre 2022,14 avenue de Lattre de Tassigny 13009 Marseille,2021-11-08,80.75,3.0,Faubourg Mazargues,Bouygues,2743.0
1039,2744,80_1_FaubourgMazargues_Bouygues,4,Appartement,NaN,405500.0,337916.67,4175.42,5010.50,SO,...,Marseille,13,novembre 2022,14 avenue de Lattre de Tassigny 13009 Marseille,2021-11-08,80.93,1.0,Faubourg Mazargues,Bouygues,2744.0
1040,2745,80_3__1_FaubourgMazargues_Bouygues,4,Appartement,NaN,433500.0,361250.00,4463.73,5356.48,SO,...,Marseille,13,novembre 2022,14 avenue de Lattre de Tassigny 13009 Marseille,2021-11-08,80.93,3.0,Faubourg Mazargues,Bouygues,2745.0
1041,2746,80_6_FaubourgMazargues_Bouygues,4,Appartement,NaN,501500.0,417916.67,5196.03,6235.24,SO,...,Marseille,13,novembre 2022,14 avenue de Lattre de Tassigny 13009 Marseille,2021-11-08,80.43,6.0,Faubourg Mazargues,Bouygues,2746.0
1042,2747,99_6_FaubourgMazargues_Bouygues,4,Appartement,NaN,598500.0,498750.00,5016.09,6019.31,NO,...,Marseille,13,novembre 2022,14 avenue de Lattre de Tassigny 13009 Marseille,2021-11-08,99.43,6.0,Faubourg Mazargues,Bouygues,2747.0

In [26]:
df.to_csv('immo_bien.csv', sep='\t', encoding='utf-8', index=False)

In [21]:
df.isna()

,Id,id_lot,nb_piece,typologie,prix_tva_reduite,prix_tva_normale,prix_HT,prix_m2_HT,prix_m2_TTC,orientation,...,ville,departement,date_fin_programme,adresse_entiere,date_extraction,surface,etage,nom_programme,promoteur,index
0,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1038,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1039,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1040,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1041,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1042,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [23]:
import json
s = df.groupby('ville')['prix_m2_TTC'].mean()
json_records = s.reset_index().to_json(orient ='records')

In [24]:
data = []
data = json.loads(json_records)
df.groupby('ville')['prix_m2_TTC'].std()

ville
Aix-en-Provence        305.048707
Angers                 401.616652
Antony                  98.861484
Bezannes               450.882775
Bois-Colombes          677.364350
                          ...
Verneuil-sur-Seine     697.639571
Villeurbanne           396.311421
VÃ©nissieux            755.578230
Woippy                 457.781230
Ã‰vry-Courcouronnes    520.717043
Name: prix_m2_TTC, Length: 63, dtype: float64

In [25]:
data

[{'ville': 'Aix-en-Provence', 'prix_m2_TTC': 5770.658},
 {'ville': 'Angers', 'prix_m2_TTC': 4514.3025},
 {'ville': 'Antony', 'prix_m2_TTC': 6923.6833333333},
 {'ville': 'Bezannes', 'prix_m2_TTC': 3938.5222222222},
 {'ville': 'Bois-Colombes', 'prix_m2_TTC': 7610.0057142857},
 {'ville': 'Bordeaux', 'prix_m2_TTC': 4885.3558461538},
 {'ville': 'Caen', 'prix_m2_TTC': 5218.9553488372},
 {'ville': 'Cancale', 'prix_m2_TTC': 4783.995},
 {'ville': 'Carnac', 'prix_m2_TTC': 5034.22},
 {'ville': 'Clermont-Ferrand', 'prix_m2_TTC': 3696.1346511628},
 {'ville': 'Conflans-Sainte-Honorine', 'prix_m2_TTC': 4919.27},
 {'ville': 'Dijon', 'prix_m2_TTC': 3755.1755172414},
 {'ville': 'Dinard', 'prix_m2_TTC': 5849.3875},
 {'ville': 'DomÃ¨ne', 'prix_m2_TTC': 3648.33},
 {'ville': 'Douai', 'prix_m2_TTC': 3104.47},
 {'ville': 'Draguignan', 'prix_m2_TTC': 4041.7454545455},
 {'ville': 'DÃ©ville-lÃ¨s-Rouen', 'prix_m2_TTC': 3079.4214285714},
 {'ville': 'Eckbolsheim', 'prix_m2_TTC': 4007.757},
 {'ville': 'Floirac', 'prix_m2_TTC': 4562.0348148148},
 {'ville': 'Givors', 'prix_m2_TTC': 3031.1566666667},
 {'ville': 'Istres', 'prix_m2_TTC': 3965.13},
 {'ville': 'JouÃ©-lÃ¨s-Tours', 'prix_m2_TTC': 4095.8453333333},
 {'ville': 'LaMotte-Servolex', 'prix_m2_TTC': 4758.745625},
 {'ville': 'LaRoche-sur-Yon', 'prix_m2_TTC': 3147.8025},
 {'ville': 'LaRochelle', 'prix_m2_TTC': 5819.3903703704},
 {'ville': 'LeMonÃªtier-les-Bains', 'prix_m2_TTC': 5773.9033333333},
 {'ville': 'LeRheu', 'prix_m2_TTC': 4258.5808695652},
 {'ville': 'LesPonts-de-CÃ©', 'prix_m2_TTC': 3045.241},
 {'ville': 'Lille', 'prix_m2_TTC': 3762.4368181818},
 {'ville': 'Linselles', 'prix_m2_TTC': 4358.0155172414},
 {'ville': 'Lyon', 'prix_m2_TTC': 8998.98},
 {'ville': 'Magny-le-Hongre', 'prix_m2_TTC': 4990.94},
 {'ville': 'Marseille', 'prix_m2_TTC': 5894.5926829268},
 {'ville': 'Metz', 'prix_m2_TTC': 3651.7682608696},
 {'ville': 'Montlouis-sur-Loire', 'prix_m2_TTC': 3233.75},
 {'ville': 'Montpellier', 'prix_m2_TTC': 5400.62},
 {'ville': 'Nancy', 'prix_m2_TTC': 3513.68},
 {'ville': 'Nantes', 'prix_m2_TTC': 4757.8204878049},
 {'ville': 'OrlÃ©ans', 'prix_m2_TTC': 4236.88},
 {'ville': 'Ouistreham', 'prix_m2_TTC': 3814.15},
 {'ville': 'Reims', 'prix_m2_TTC': 5687.555},
 {'ville': 'Rennes', 'prix_m2_TTC': 5380.18},
 {'ville': 'Rouen', 'prix_m2_TTC': 4254.4642857143},
 {'ville': 'Royan', 'prix_m2_TTC': 4234.5225},
 {'ville': 'Saint-AndrÃ©-de-la-Roche', 'prix_m2_TTC': 5443.33875},
 {'ville': 'Saint-Jean-le-Blanc', 'prix_m2_TTC': 3767.1953333333},
 {'ville': 'Saint-Malo', 'prix_m2_TTC': 5743.4733333333},
 {'ville': 'Saint-Max', 'prix_m2_TTC': 3242.61},
 {'ville': 'Saint-Philbert-de-Grand-Lieu', 'prix_m2_TTC': 3172.2042105263},
 {'ville': 'Saint-Ã‰tienne-de-Crossey', 'prix_m2_TTC': 2951.585},
 {'ville': 'Schiltigheim', 'prix_m2_TTC': 4748.9731034483},
 {'ville': 'Strasbourg', 'prix_m2_TTC': 4185.5872580645},
 {'ville': 'SÃ©nÃ©', 'prix_m2_TTC': 4125.175},
 {'ville': 'Toulon', 'prix_m2_TTC': 4847.0618181818},
 {'ville': 'Toulouse', 'prix_m2_TTC': 4470.4760526316},
 {'ville': 'Tours', 'prix_m2_TTC': 3703.076},
 {'ville': 'Vannes', 'prix_m2_TTC': 5872.1444444444},
 {'ville': 'Vanves', 'prix_m2_TTC': 9225.804},
 {'ville': 'Verneuil-sur-Seine', 'prix_m2_TTC': 5116.306},
 {'ville': 'Villeurbanne', 'prix_m2_TTC': 5254.909},
 {'ville': 'VÃ©nissieux', 'prix_m2_TTC': 4373.7225},
 {'ville': 'Woippy', 'prix_m2_TTC': 3024.9685714286},
 {'ville': 'Ã‰vry-Courcouronnes', 'prix_m2_TTC': 3727.343125}]